spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #habilitando o localizador de microserviços
          lower-case-service-id: true #localizar eles em caixa baixa sempre

server:
  port: 8080 #tanto o eureka quanto o gateway nao preciso ficar subindo instancias, eles tem porta fixa

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka